config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "about", to: "pages#about"

  resources :cocktails, only: [ :index, :new, :show, :create, :edit, :update ] do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
  # never nest the destroy route
  mount Attachinary::Engine => "/attachinary"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_attachment :photo
  validates :name, presence: true, uniqueness: true

  def self.search(search)
    where("name ILIKE ?", "%#{search}%")
  end
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :cocktail, uniqueness: { scope: :ingredient}
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:edit, :update, :show]

  def index
   @cocktails = Cocktail.all
   if params[:search]
     @cocktails = Cocktail.search(params[:search]).order("created_at DESC")
   else
     @cocktails = Cocktail.all.order('created_at DESC')
   end
  end

  def show
  end

  def new # GET /tasks/new
    @cocktail = Cocktail.new
  end

  def create # POST /tasks
    @cocktail = Cocktail.new(cocktail_params)
    # save method returns true when record enters database
    if @cocktail.save
      redirect_to new_cocktail_dose_path(@cocktail)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @cocktail.update(cocktail_params)
    # save method returns true when record enters database
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'edit'
    end
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo, :picture)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    # we need @restaurant in our `simple_form_for`
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  # inside create we need the same instances as in new
  #  so we need an @restaurant and a @review
  def create
    # set a new empty dose
    @dose = Dose.new(dose_params)
    # find the cocktail the dose is for
    @cocktail = Cocktail.find(params[:cocktail_id])
    # assign newly dose to this cocktail: ASSOCIATION
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy # DELETE /doses/:id
    @dose = Dose.find(params[:id])
    @dose.destroy
    # no need for app/views/tasks/destroy.html.erb
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
    #  Here the params need to be just like in the schema
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home

  end

  def about

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cocktails/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
      <div class="cocktail-form">
        <%= simple_form_for(@cocktail) do |f| %>
          <%= f.input :name %>
          <%= f.input :photo, as: :attachinary %>
          <%= f.submit "Save", class: "add-btn" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/edit.html.erb
<div class="new-cocktail-layout">
  <div class="new-header">
    <h1>Edit the <%= @cocktail.name %> cocktail</h1>
  </div>
  <div class="new-cocktail-form">
    <%= render 'form', { action: 'Edit'} %>
  </div>
</div>

app/views/cocktails/index.html.erb
<div class="cocktails-layout">
  <div class="cocktails-header">
    <h1>ALL COCKTAILS</h1>
    <%= link_to new_cocktail_path, class: 'add-btn' do %>
      Add a new cocktail
    <% end %>
  </div>

  <div class="cocktails-search-result text-center">
    <% if @cocktails.present? %>
      <p>Here is what we found:</p>
    <% else %>
      <p>Sorry, we haven't found a cocktail named "<%= params[:search] %>".</p>
      <%= link_to 'Search again', root_path, class: 'search-link' %>
    <% end %>
  </div>

  <div class="cocktails-list">
    <div class="container-fluid">
      <div class="row">
        <% @cocktails.each do |cocktail| %>
          <div class="col-xs-12 col-sm-6 col-md-4">
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('http://www.athensrumfestival.com/wp-content/uploads/2016/06/test-search.jpg');">
              <div class="card-category">Trendy</div>
              <div class="card-description">
                <h2><%= cocktail.name %></h2>
                <%= link_to "See details", cocktail_path(cocktail), class: "btn btn-primary"  %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="new-cocktail-layout">
  <div class="new-header">
    <h1>Add a new cocktail</h1>
  </div>
  <div class="new-cocktail-form">
    <%= render 'form', { action: 'Add' } %>
    <div class="new-cocktail-bonus">
      <%= link_to '< Go back', cocktails_path, class: 'go-back-btn' %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="cocktail-show-layout">
  <div class="cocktail-intro">
    <h1><%= @cocktail.name %></h1>

    <div class="cocktail-photo">
      <% if @cocktail.photo? %>
        <% picture_path = "http://res.cloudinary.com/dqonjhrsw/image/upload/" + @cocktail.photo.path %>
      <% else %>
        <% picture_path = @cocktail.picture %>
      <% end %>

      <%= image_tag(picture_path, width: 250, height: 250) %>
    </div>
  </div>
  <div class="cocktail-recipe">
    <div class="cocktail-ingredients">
      <div class="ingredients-header">
        <h2>All you need to enjoy this delicious coktails is:</h2>
      </div>
      <div class="ingredients-list"></div>
      <% @cocktail.doses.each do |dose| %>
        <p>
          - <%= dose.ingredient.name %> : <%= dose.description %>
          <%= link_to dose_path(dose), method: :delete, data: {
              confirm: 'Are you sure?',
              text: 'You won\'t be able to revert this!',
              'confirm-button-text': 'Yes, delete it!',
              'cancel-button-text': 'Cancel',
              'sweet-alert-type': 'warning',
              'confirm-button-color': 'rgb(126, 198, 76)',
              'cancel-button-color': 'rgb(167,0,42)'
            } do %>
            <i class="fa fa-trash"></i>
          <% end %>
        </p>
        <% end %>
    </div>
  </div>
  <div class="cocktail-ctas">
    <%= link_to "See all", cocktails_path, class: "show-btn" %>

    <%= link_to "Edit", edit_cocktail_path(@cocktail), class: "show-btn" %>

    <%= link_to "Add a dose", new_cocktail_dose_path(@cocktail), class: "show-btn" %>
  </div>
  <div class="cocktail-dose-form">
    <p>Here will go the dose form later</p>
  </div>
</div>

app/views/doses/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <%= simple_form_for [@cocktail, @dose] do |f| %>
        <%= f.input :description %>
        <%= f.association :ingredient %>
        <%= f.submit "add a dose", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Miss Cocktail</title>
    <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= favicon_link_tag "logo.png" %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://cdn.rawgit.com/konpa/devicon/df6431e323547add1b4cf45992913f15286456d3/devicon.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= cloudinary_js_config %>
  </head>

  <body>
    <%= render 'shared/navbar'%>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="about-layout">
  <div class="about-title">
    <h1>ABOUT MISS COCKTAIL</h1>
  </div>
  <div class="about-creator">
    <div class="creator-card">
      <div class="creator-avatar"></div>
      <div class="creator-infos">
        <a href="https://github.com/SoundOfSun?tab=repositories" target="_blank" class="gh-user-link">
            <i class="fa fa-github" aria-hidden="true"></i>  SoundOfSun
        </a>
        <p>Junior front-end developer</p>
        <p>
          This rails app is part of the Le Wagon coding bootcamp exercises. If you would like to learn how to code in RoR and Javascript, check out <a href="https://www.lewagon.com/" target="_blank" class="lewagon-link">Le Wagon</a>. <br>
          The design for this website has been inspired by Divan Raj's work. See his work on dribble here: <a href="https://dribbble.com/shots/3873826-Event-website-header" class="dribble-link" target="_blank">
            <i class="fa fa-info-circle" aria-hidden="true"></i>
          </a>
        </p>
      </div>
    </div>
  </div>
  <div class="about-tech">
    <div class="tech-list">
      <i class="devicon-html5-plain"></i>
      <i class="devicon-css3-plain"></i>
      <i class="devicon-bootstrap-plain"></i>
      <i class="devicon-sass-original"></i>
      <i class="devicon-javascript-plain"></i>
      <i class="devicon-jquery-plain"></i>
      <i class="devicon-ruby-plain"></i>
      <i class="devicon-rails-plain"></i>
      <i class="devicon-postgresql-plain"></i>
      <i class="devicon-heroku-original"></i>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="home-layout">
  <div class="home-header">
    <div class="home-header-content">
      <h6>Welcome to <span id="title">Miss</span></h6>
      <div class="phone-home-links hidden-md hidden-lg">
        <a href="#" class="sns-btn-phone">
          <i class="fa fa-twitter" aria-hidden="true"></i>
        </a>
        <a href="#" class="sns-btn-phone">
          <i class="fa fa-instagram" aria-hidden="true"></i>
        </a>
        <a href="#" class="sns-btn-phone">
          <i class="fa fa-facebook" aria-hidden="true"></i>
        </a>
      </div>
    </div>
  </div>
  <div class="home-input">
    <div class="home-form">
      <%= form_tag(cocktails_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search for a cocktail" %>
      <%= submit_tag "Search" %>
      <% end %>
    </div>
  </div>
  <div class="home-footer">
    <div class="home-links hidden-xs hidden-sm">
      <a href="#" class="sns-btn">
        <i class="fa fa-twitter" aria-hidden="true"></i>
      </a>
      <a href="#" class="sns-btn">
        <i class="fa fa-instagram" aria-hidden="true"></i>
      </a>
      <a href="#" class="sns-btn">
        <i class="fa fa-facebook" aria-hidden="true"></i>
      </a>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fa fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag ('logo.png') %> Miss Coktail
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <%= link_to about_path, class: "navbar-wagon-item navbar-wagon-link" do %>
      About
    <% end %>
    <%= link_to cocktails_path, class: "navbar-wagon-item navbar-wagon-link" do %>
      Cocktails
    <% end %>

    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="https://kitt.lewagon.com/placeholder/users/SoundOfSun" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to about_path, class: "navbar-wagon-item navbar-wagon-link" do %>
              About
            <% end %>
          </li>
          <li>
            <%= link_to cocktails_path, class: "navbar-wagon-item navbar-wagon-link" do %>
              Cocktails
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to about_path, class: "navbar-wagon-item navbar-wagon-link" do %>
            About
          <% end %>
        </li>
        <li>
          <%= link_to cocktails_path, class: "navbar-wagon-item navbar-wagon-link" do %>
            Cocktails
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>